# Remove version for modern Docker Compose

# Production override for compose.yaml
# Usage: docker compose -f compose.yaml -f compose.prod.yaml up

services:
  # Production Web Application
  web:
    build:
      target: production
    environment:
      - NODE_ENV=production
    volumes:
      # Remove development volume mounts for production
      - /dev/null:/app/src:ro
    command: npm start
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # Production Database with performance tuning
  db:
    environment:
      # Production database performance settings
      POSTGRES_SHARED_PRELOAD_LIBRARIES: pg_stat_statements
    command: >
      postgres
      -c max_connections=100
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # Production Scraper with resource limits
  scraper:
    volumes:
      # Remove development volume mounts for production
      - scraper_logs:/app/logs
    environment:
      - SCRAPING_INTERVAL_SECONDS=300  # 5 minutes in production
      - MAX_CONCURRENT_SCRAPES=5       # More concurrent scrapes in production
      - LOG_LEVEL=warning              # Less verbose logging
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 256M
          cpus: '0.1'

  # Production Redis with persistence
  redis:
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.1'
        reservations:
          memory: 128M
          cpus: '0.05'

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - web
    networks:
      - tail-match-network
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'

volumes:
  nginx_logs:
    driver: local