services:
  postgres:
    image: postgres:15-alpine
    container_name: tail-match-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-tailmatch}
      POSTGRES_USER: ${DB_USER:-tailmatch_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dev_password_123}
      TZ: Asia/Tokyo
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - tail-match-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-tailmatch_user} -d ${DB_NAME:-tailmatch}"]
      interval: 10s
      timeout: 5s
      retries: 5

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tail-match-nextjs
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${DB_USER:-tailmatch_user}:${DB_PASSWORD:-dev_password_123}@postgres:5432/${DB_NAME:-tailmatch}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER:-tailmatch_user}
      - DB_PASSWORD=${DB_PASSWORD:-dev_password_123}
      - DB_NAME=${DB_NAME:-tailmatch}
    ports:
      - "${NEXT_PORT:-3000}:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tail-match-network
    command: npm run dev

  python-scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: tail-match-scraper
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-tailmatch_user}:${DB_PASSWORD:-dev_password_123}@postgres:5432/${DB_NAME:-tailmatch}
      - PYTHONPATH=/app
    volumes:
      - ./scraper:/app
      - /app/.venv  # Poetry仮想環境を保持
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tail-match-network
    profiles:
      - scraper  # デフォルトでは起動しない
    command: poetry run python main.py --test-db

volumes:
  postgres_data:
    driver: local

networks:
  tail-match-network:
    driver: bridge